package com.lmlasmo.tasklist.doc.controller.account;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import com.lmlasmo.tasklist.doc.SimpleApiDoc;
import com.lmlasmo.tasklist.doc.StatusResponseApiDoc;

import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@SecurityRequirement(name = "bearerAuth")
@SimpleApiDoc(
		summary = "Link a new email to the user",
		description = """
					Links a new email address to the authenticated user.
					
					The email address provided cannot exist in the system.  
				    The confirmation code used must have been generated by the /api/auth/email/confirmation
				    endpoint with scope **LINK**.
					""",
		success = @StatusResponseApiDoc(status = 204, message = "Email successfully linked"),
		errors = {
				@StatusResponseApiDoc(status = 400, message = "Invalid data, missing data, invalid code, or email already in use")
			}
		)
@Tag(name = "account-controller")
public @interface LinkEmailApiDoc {}
