CREATE TABLE IF NOT EXISTS users(

id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role VARCHAR(50) NOT NULL

);

CREATE TABLE IF NOT EXISTS tasks(

id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
task TEXT NOT NULL,
timestamp TIMESTAMP NOT NULL,
status VARCHAR(50) NOT NULL,
user_id INT NOT NULL,

FOREIGN KEY (user_id) REFERENCES users(id)

);
