ALTER TABLE users
ADD COLUMN row_version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE tasks
ADD COLUMN row_version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE subtasks
ADD COLUMN row_version BIGINT NOT NULL DEFAULT 0;