package com.lmlasmo.tasklist.doc.controller.auth;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import com.lmlasmo.tasklist.doc.SimpleApiDoc;
import com.lmlasmo.tasklist.doc.StatusResponseApiDoc;

import io.swagger.v3.oas.annotations.tags.Tag;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@SimpleApiDoc(
		summary = "Change the user password.",
		description = """
					Change the password for the user associated with the provided email address.
				
					The confirmation code used in this process must have been generated by the
					/api/auth/email/confirmation endpoint with the **RECOVERY** scope.
					""",
		success = @StatusResponseApiDoc(status = 204, message = "Password updated successfully"),
		errors = {
				@StatusResponseApiDoc(status = 400, message = "Invalid data, missing data, or invalid code"),
				@StatusResponseApiDoc(status = 404, message = "Email not found"),
				@StatusResponseApiDoc(status = 409, message = "The user was modified or removed during the process"),
			}
		)
@Tag(name = "auth-controller")
public @interface PasswordRecoveryApiDoc {}
